# Generated by Django 6.0.1 on 2026-01-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 200 символов', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='URL-friendly название (латинские буквы, цифры, дефисы)', max_length=200, unique=True, verbose_name='URL-адрес')),
                ('description', models.TextField(blank=True, help_text='Необязательное описание категории', null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Отображается ли категория на сайте', verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
