# Generated by Django 6.0.1 on 2026-01-29 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимум 200 символов', max_length=200, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Уникальное название для URL', max_length=255, unique=True, verbose_name='URL-friendly название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Полное описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('stock', models.IntegerField(default=0, verbose_name='Количество на складе')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для продажи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='myapp.category', verbose_name='Категория товара')),
            ],
        ),
    ]
