# Generated by Django 6.0.1 on 2026-02-19 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_products_created_at_alter_products_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
